import axios from 'axios';
import authHeader from './auth-header';

/**
 * Base URL for the API
 * @constant {string}
 */
const API_URL = 'http://localhost:8080/api';

/**
 * Axios instance configured with the base URL and authorization headers.
 *
 * This instance is pre-configured with the base URL of the API and includes
 * the authorization headers generated by the `authHeader` function. By using this
 * instance, you ensure that all requests include the necessary authentication headers
 * and are directed to the correct API endpoint.
 *
 * @see authHeader
 */
const axiosInstance = axios.create({
    baseURL: API_URL,
    headers: authHeader(),
});

export default axiosInstance;
